package com.telegrambot.marketplace.enums;

public enum StateType {
    NONE,
    CREATE_PASSWORD,
    ENTER_REFERRAL,
    ORDER,
    ADD_PRODUCT_PORTION,
    PRODUCT_PORTION_COUNTRY_CITY_DISTRICT,
    PRODUCT_PORTION_CATEGORY_SUBCATEGORY_PRODUCT,
    PRODUCT_PORTION_LATITUDE_LONGITUDE_AMOUNT,
    PRODUCT_PORTION_PHOTO;
}
